name: MDF_Sat
description: Приложение для просмотра и заказа МДФ фасадов.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.14.4
  http: ^1.2.0  # пакет для работы с API

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png  # твой логотип
    - assets/icon.png
    - assets/fasad1.png
    - assets/fasad2.png
    - assets/fasad3.png
    - assets/fasad4.png
    - assets/fasad5.png 

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
